-- Q11 phase 2 — swap every primary-key column default from
-- `cuid()` / `gen_random_uuid()` (v4) to `uuidv7()`.
--
-- Pre-requisite: the pg_uuidv7 extension must be installed (see
-- migration 20260503120000_install_pg_uuidv7).
--
-- Strategy: ALTER COLUMN ... SET DEFAULT for every `id` column whose
-- type is `uuid` or text (cuid). New rows get UUID v7; legacy rows
-- keep their existing string IDs. v7 and v4 share the same UUID
-- textual form so legacy IDs continue to validate against
-- `z.string().uuid()`.
--
-- Generated by introspecting the Prisma schema files. If a new model
-- is added, add an ALTER for it here.

-- Identity / users
ALTER TABLE IF EXISTS "User"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Permission"                 ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Role"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "UserRoleAssignment"         ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "AccessModifier"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "UserConsent"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "AuditLog"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "RefreshToken"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Resumes
ALTER TABLE IF EXISTS "Resume"                     ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeSection"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeSectionItem"          ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "SectionType"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeStyle"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeShare"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeVersion"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "QualityScoreSnapshot"       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Jobs / applications
ALTER TABLE IF EXISTS "Job"                        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "JobApplication"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "JobApplicationEvent"        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "JobBookmark"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "TrackedApplication"         ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Social
ALTER TABLE IF EXISTS "Follow"                     ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Connection"                 ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Activity"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "SkillEndorsement"           ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Feed / posts
ALTER TABLE IF EXISTS "Post"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "PostComment"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Reaction"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Chat / collaboration
ALTER TABLE IF EXISTS "ChatConversation"           ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "Message"                    ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "BlockedUser"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "ResumeCollaboration"        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Notifications
ALTER TABLE IF EXISTS "Notification"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Imports / integrations
ALTER TABLE IF EXISTS "ResumeImport"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "GithubProfile"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Catalog
ALTER TABLE IF EXISTS "MecInstitution"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "MecCourse"                  ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "TechSkill"                  ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "SpokenLanguage"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Platform
ALTER TABLE IF EXISTS "FeatureFlag"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "WebhookConfig"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "WebhookDelivery"            ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE IF EXISTS "PlatformEvent"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Sanity check — fail if pg_uuidv7 isn't actually available so we
-- never silently fall back to NULL ids.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_uuidv7') THEN
    RAISE EXCEPTION 'pg_uuidv7 extension is required for this migration. Run 20260503120000_install_pg_uuidv7 first.';
  END IF;
END$$;
