-- Q11 phase 2 — swap every primary-key column default from
-- `cuid()` / `gen_random_uuid()` (v4) to `uuidv7()`.
--
-- Pre-requisite: the pg_uuidv7 extension must be installed (see
-- migration 20260503120000_install_pg_uuidv7).
--
-- Strategy: ALTER COLUMN ... SET DEFAULT for every `id` column whose
-- type is `uuid` or text (cuid). New rows get UUID v7; legacy rows
-- keep their existing string IDs. v7 and v4 share the same UUID
-- textual form so legacy IDs continue to validate against
-- `z.string().uuid()`.
--
-- Generated by introspecting the Prisma schema files. If a new model
-- is added, add an ALTER for it here.

-- Identity / users
ALTER TABLE "User"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Permission"                 ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Role"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "UserRoleAssignment"         ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "AccessModifier"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "UserConsent"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "AuditLog"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "RefreshToken"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Resumes
ALTER TABLE "Resume"                     ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeSection"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeSectionItem"          ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "SectionType"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeStyle"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeShare"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeVersion"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "QualityScoreSnapshot"       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Jobs / applications
ALTER TABLE "Job"                        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "JobApplication"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "JobApplicationEvent"        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "JobBookmark"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "TrackedApplication"         ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Social
ALTER TABLE "Follow"                     ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Connection"                 ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Activity"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "SkillEndorsement"           ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Feed / posts
ALTER TABLE "Post"                       ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "PostComment"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Reaction"                   ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Chat / collaboration
ALTER TABLE "ChatConversation"           ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "Message"                    ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "BlockedUser"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "ResumeCollaboration"        ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Notifications
ALTER TABLE "Notification"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Imports / integrations
ALTER TABLE "ResumeImport"               ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "GithubProfile"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Catalog
ALTER TABLE "MecInstitution"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "MecCourse"                  ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "TechSkill"                  ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "SpokenLanguage"             ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Platform
ALTER TABLE "FeatureFlag"                ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "WebhookConfig"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "WebhookDelivery"            ALTER COLUMN "id" SET DEFAULT uuidv7()::text;
ALTER TABLE "PlatformEvent"              ALTER COLUMN "id" SET DEFAULT uuidv7()::text;

-- Sanity check — fail if pg_uuidv7 isn't actually available so we
-- never silently fall back to NULL ids.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_uuidv7') THEN
    RAISE EXCEPTION 'pg_uuidv7 extension is required for this migration. Run 20260503120000_install_pg_uuidv7 first.';
  END IF;
END$$;
