/**
 * Contract: every leaf in `route.params` / `route.query` / `route.body` /
 * `route.response` declares `.openapi({ example })` (or `.openapi({ examples })`)
 * — or matches an auto-derive rule (name-based) — or the schema is in the
 * exempt list (recursive bounded patterns).
 *
 * Failure mode: a single failing assertion that prints the full backlog of
 * offenders. The list is the migration roadmap for Workstream A of the
 * Caminho A plan (Dredd 1684 passing without gambiarra).
 */

import { beforeAll, describe, expect, test } from 'bun:test';
import { readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { type ZodSchema, z } from 'zod';
import type { Route } from '@/shared-kernel/http/route';
import {
  EXAMPLE_BIO,
  EXAMPLE_CONVERSATION_ID,
  EXAMPLE_COUNT,
  EXAMPLE_DATE_ONLY,
  EXAMPLE_DESCRIPTION,
  EXAMPLE_EMAIL,
  EXAMPLE_GENERIC_ID,
  EXAMPLE_GITHUB_URL,
  EXAMPLE_HEX_COLOR,
  EXAMPLE_ISO_DATETIME,
  EXAMPLE_JOB_ID,
  EXAMPLE_LINKEDIN_URL,
  EXAMPLE_LOCALE,
  EXAMPLE_LOCATION,
  EXAMPLE_NAME,
  EXAMPLE_NOTIFICATION_ID,
  EXAMPLE_PASSWORD,
  EXAMPLE_PHONE,
  EXAMPLE_POST_ID,
  EXAMPLE_RESUME_ID,
  EXAMPLE_SCORE,
  EXAMPLE_SLUG,
  EXAMPLE_TAG,
  EXAMPLE_TITLE,
  EXAMPLE_TOKEN,
  EXAMPLE_URL,
  EXAMPLE_USER_ID,
  EXAMPLE_USERNAME,
} from '@/shared-kernel/schemas/params/example-values.const';
import { findOffenders } from '../shared/zod-leaf-walker';

extendZodWithOpenApi(z);

const SRC_DIR = resolve(__dirname, '../../../src');

function* walkRoutesFiles(dir: string): Generator<string> {
  for (const entry of readdirSync(dir).sort()) {
    if (entry === 'node_modules' || entry === '__tests__' || entry === 'testing') continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) yield* walkRoutesFiles(full);
    else if (st.isFile() && entry.endsWith('.routes.ts') && !entry.endsWith('.spec.ts')) {
      yield full;
    }
  }
}

function isRouteArray(value: unknown): value is ReadonlyArray<Route> {
  if (!Array.isArray(value) || value.length === 0) return false;
  const first = value[0] as Partial<Route> | undefined;
  return (
    typeof first === 'object' &&
    first !== null &&
    typeof (first as Route).method === 'string' &&
    typeof (first as Route).path === 'string' &&
    typeof (first as Route).handler === 'function'
  );
}

interface CollectedRoute {
  readonly file: string;
  readonly route: Route;
}

const collected: CollectedRoute[] = [];

beforeAll(async () => {
  for (const file of walkRoutesFiles(SRC_DIR)) {
    try {
      const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
      for (const value of Object.values(mod)) {
        if (isRouteArray(value)) {
          for (const route of value) collected.push({ file, route: route as Route });
        }
      }
    } catch {
      // Module load failure surfaces in tsc / route-descriptors contract.
    }
  }
});

const NAME_TO_EXAMPLE: ReadonlyMap<string, string> = new Map<string, string>([
  ['userId', EXAMPLE_USER_ID],
  ['authorId', EXAMPLE_USER_ID],
  ['actorId', EXAMPLE_USER_ID],
  ['ownerId', EXAMPLE_USER_ID],
  ['recipientId', EXAMPLE_USER_ID],
  ['senderId', EXAMPLE_USER_ID],
  ['createdBy', EXAMPLE_USER_ID],
  ['updatedBy', EXAMPLE_USER_ID],
  ['resumeId', EXAMPLE_RESUME_ID],
  ['jobId', EXAMPLE_JOB_ID],
  ['postId', EXAMPLE_POST_ID],
  ['originalPostId', EXAMPLE_POST_ID],
  ['parentPostId', EXAMPLE_POST_ID],
  ['threadId', EXAMPLE_POST_ID],
  ['conversationId', EXAMPLE_CONVERSATION_ID],
  ['notificationId', EXAMPLE_NOTIFICATION_ID],
  ['id', EXAMPLE_GENERIC_ID],
  ['parentId', EXAMPLE_GENERIC_ID],
  ['commentId', EXAMPLE_GENERIC_ID],
  ['shareId', EXAMPLE_GENERIC_ID],
  ['versionId', EXAMPLE_GENERIC_ID],
  ['sectionId', EXAMPLE_GENERIC_ID],
  ['itemId', EXAMPLE_GENERIC_ID],
  ['skillId', EXAMPLE_GENERIC_ID],
  ['importId', EXAMPLE_GENERIC_ID],
  ['applicationId', EXAMPLE_GENERIC_ID],
  ['modifierId', EXAMPLE_GENERIC_ID],
  ['styleId', EXAMPLE_GENERIC_ID],
  ['themeId', EXAMPLE_GENERIC_ID],
  ['flagId', EXAMPLE_GENERIC_ID],
  ['questionId', EXAMPLE_GENERIC_ID],
  ['eventId', EXAMPLE_GENERIC_ID],
  ['logId', EXAMPLE_GENERIC_ID],
  ['nicheId', EXAMPLE_GENERIC_ID],
  ['areaId', EXAMPLE_GENERIC_ID],
  ['languageId', EXAMPLE_GENERIC_ID],
  ['stepId', EXAMPLE_GENERIC_ID],
  ['key', EXAMPLE_SLUG],
  ['code', EXAMPLE_SLUG],
  ['slug', EXAMPLE_SLUG],
  ['nicheSlug', EXAMPLE_SLUG],
  ['sectionTypeKey', EXAMPLE_SLUG],
  ['sectionKey', EXAMPLE_SLUG],
  ['kind', EXAMPLE_SLUG],
  ['type', EXAMPLE_SLUG],
  ['subtype', EXAMPLE_SLUG],
  ['areaType', EXAMPLE_SLUG],
  ['provider', 'github'],
  ['section', 'profile'],
  ['username', EXAMPLE_USERNAME],
  ['handle', EXAMPLE_USERNAME],
  ['email', EXAMPLE_EMAIL],
  ['emailAddress', EXAMPLE_EMAIL],
  ['recipientEmail', EXAMPLE_EMAIL],
  ['password', EXAMPLE_PASSWORD],
  ['currentPassword', EXAMPLE_PASSWORD],
  ['newPassword', EXAMPLE_PASSWORD],
  ['passwordConfirmation', EXAMPLE_PASSWORD],
  ['token', EXAMPLE_TOKEN],
  ['accessToken', EXAMPLE_TOKEN],
  ['refreshToken', EXAMPLE_TOKEN],
  ['resetToken', EXAMPLE_TOKEN],
  ['verificationToken', EXAMPLE_TOKEN],
  ['inviteToken', EXAMPLE_TOKEN],
  ['phone', EXAMPLE_PHONE],
  ['phoneNumber', EXAMPLE_PHONE],
  ['location', EXAMPLE_LOCATION],
  ['city', EXAMPLE_LOCATION],
  ['region', EXAMPLE_LOCATION],
  ['country', 'BR'],
  ['url', EXAMPLE_URL],
  ['logoUrl', EXAMPLE_URL],
  ['photoUrl', EXAMPLE_URL],
  ['photoURL', EXAMPLE_URL],
  ['avatarUrl', EXAMPLE_URL],
  ['imageUrl', EXAMPLE_URL],
  ['thumbnailUrl', EXAMPLE_URL],
  ['previewUrl', EXAMPLE_URL],
  ['downloadUrl', EXAMPLE_URL],
  ['redirectUrl', EXAMPLE_URL],
  ['callbackUrl', EXAMPLE_URL],
  ['siteUrl', EXAMPLE_URL],
  ['publicUrl', EXAMPLE_URL],
  ['shareUrl', EXAMPLE_URL],
  ['linkUrl', EXAMPLE_URL],
  ['applyUrl', EXAMPLE_URL],
  ['website', EXAMPLE_URL],
  ['linkedin', EXAMPLE_LINKEDIN_URL],
  ['linkedinUrl', EXAMPLE_LINKEDIN_URL],
  ['github', EXAMPLE_GITHUB_URL],
  ['githubUrl', EXAMPLE_GITHUB_URL],
  ['name', EXAMPLE_NAME],
  ['fullName', EXAMPLE_NAME],
  ['firstName', 'Fixture'],
  ['lastName', 'User'],
  ['displayName', EXAMPLE_NAME],
  ['authorName', EXAMPLE_NAME],
  ['title', EXAMPLE_TITLE],
  ['jobTitle', EXAMPLE_TITLE],
  ['headline', EXAMPLE_TITLE],
  ['subject', EXAMPLE_TITLE],
  ['summary', EXAMPLE_DESCRIPTION],
  ['description', EXAMPLE_DESCRIPTION],
  ['content', EXAMPLE_DESCRIPTION],
  ['body', EXAMPLE_DESCRIPTION],
  ['message', EXAMPLE_DESCRIPTION],
  ['note', EXAMPLE_DESCRIPTION],
  ['notes', EXAMPLE_DESCRIPTION],
  ['caption', EXAMPLE_DESCRIPTION],
  ['excerpt', EXAMPLE_DESCRIPTION],
  ['comment', EXAMPLE_DESCRIPTION],
  ['feedback', EXAMPLE_DESCRIPTION],
  ['reason', EXAMPLE_DESCRIPTION],
  ['bio', EXAMPLE_BIO],
  ['about', EXAMPLE_BIO],
  ['tagline', EXAMPLE_BIO],
  ['hashtag', EXAMPLE_TAG],
  ['tag', EXAMPLE_TAG],
  ['color', EXAMPLE_HEX_COLOR],
  ['accentColor', EXAMPLE_HEX_COLOR],
  ['bannerColor', EXAMPLE_HEX_COLOR],
  ['palette', 'default'],
  ['theme', 'default'],
  ['style', 'default'],
  ['layout', 'default'],
  ['lang', 'en'],
  ['locale', EXAMPLE_LOCALE],
  ['language', EXAMPLE_LOCALE],
  ['primaryLanguage', EXAMPLE_LOCALE],
  ['createdAt', EXAMPLE_ISO_DATETIME],
  ['updatedAt', EXAMPLE_ISO_DATETIME],
  ['publishedAt', EXAMPLE_ISO_DATETIME],
  ['expiresAt', EXAMPLE_ISO_DATETIME],
  ['deletedAt', EXAMPLE_ISO_DATETIME],
  ['archivedAt', EXAMPLE_ISO_DATETIME],
  ['scheduledAt', EXAMPLE_ISO_DATETIME],
  ['lastLoginAt', EXAMPLE_ISO_DATETIME],
  ['lastSeenAt', EXAMPLE_ISO_DATETIME],
  ['readAt', EXAMPLE_ISO_DATETIME],
  ['sentAt', EXAMPLE_ISO_DATETIME],
  ['startedAt', EXAMPLE_ISO_DATETIME],
  ['finishedAt', EXAMPLE_ISO_DATETIME],
  ['completedAt', EXAMPLE_ISO_DATETIME],
  ['acceptedAt', EXAMPLE_ISO_DATETIME],
  ['declinedAt', EXAMPLE_ISO_DATETIME],
  ['canceledAt', EXAMPLE_ISO_DATETIME],
  ['cancelledAt', EXAMPLE_ISO_DATETIME],
  ['emailVerifiedAt', EXAMPLE_ISO_DATETIME],
  ['emailVerified', EXAMPLE_ISO_DATETIME],
  ['onboardingCompletedAt', EXAMPLE_ISO_DATETIME],
  ['startDate', EXAMPLE_DATE_ONLY],
  ['endDate', EXAMPLE_DATE_ONLY],
  ['date', EXAMPLE_DATE_ONLY],
  ['dob', EXAMPLE_DATE_ONLY],
  ['birthDate', EXAMPLE_DATE_ONLY],
  ['count', String(EXAMPLE_COUNT)],
  ['total', String(EXAMPLE_COUNT)],
  ['score', String(EXAMPLE_SCORE)],
  ['atsScore', String(EXAMPLE_SCORE)],
  ['styleScore', String(EXAMPLE_SCORE)],
  ['fitScore', String(EXAMPLE_SCORE)],
  ['matchScore', String(EXAMPLE_SCORE)],
  ['weight', '1'],
  ['order', '0'],
  ['position', '0'],
  ['rank', '1'],
  ['index', '0'],
  ['version', '1'],
  ['page', '1'],
  ['limit', '20'],
  ['offset', '0'],
  ['size', '20'],
  ['perPage', '20'],
  ['cursor', 'cursor-fixture'],
  ['nextCursor', 'cursor-fixture'],
  ['prevCursor', 'cursor-fixture'],
  ['hasNext', 'false'],
  ['hasPrev', 'false'],
  ['totalPages', '1'],
  ['min', '0'],
  ['max', '100'],
  ['minSalaryUsd', '50000'],
  ['salaryRange', '50000-80000'],
  ['ipAddress', '127.0.0.1'],
  ['userAgent', 'Mozilla/5.0 (X11; Linux x86_64)'],
  ['mimeType', 'image/png'],
  ['contentType', 'image/png'],
  ['extension', 'png'],
  ['fileName', 'fixture.png'],
  ['filename', 'fixture.png'],
  ['filePath', '/fixture.png'],
  ['path', '/fixture.png'],
  ['domain', 'profile.local'],
  ['hostname', 'profile.local'],
  ['ip', '127.0.0.1'],
  ['port', '3010'],
  ['hash', 'fixture-hash'],
  ['etag', 'fixture-etag'],
  ['rev', 'fixture-rev'],
  ['sourceLanguage', 'pt'],
  ['targetLanguage', 'en'],
  ['detectedLanguage', 'pt'],
  ['namePtBr', `${EXAMPLE_NAME} (pt-BR)`],
  ['nameEn', EXAMPLE_NAME],
  ['descriptionPtBr', `${EXAMPLE_DESCRIPTION} (pt-BR)`],
  ['descriptionEn', EXAMPLE_DESCRIPTION],
  ['titlePtBr', `${EXAMPLE_TITLE} (pt-BR)`],
  ['titleEn', EXAMPLE_TITLE],
  ['label', EXAMPLE_TITLE],
  ['labelPtBr', `${EXAMPLE_TITLE} (pt-BR)`],
  ['labelEn', EXAMPLE_TITLE],
  ['placeholder', EXAMPLE_TITLE],
  ['placeholderPtBr', `${EXAMPLE_TITLE} (pt-BR)`],
  ['placeholderEn', EXAMPLE_TITLE],
  ['icon', 'sparkles'],
  ['iconName', 'sparkles'],
  ['emoji', '✨'],
  ['image', EXAMPLE_URL],
  ['avatar', EXAMPLE_URL],
  ['banner', EXAMPLE_URL],
  ['cover', EXAMPLE_URL],
  ['source', EXAMPLE_SLUG],
  ['target', EXAMPLE_SLUG],
  ['origin', EXAMPLE_SLUG],
  ['destination', EXAMPLE_SLUG],
  ['namespace', EXAMPLE_SLUG],
  ['category', EXAMPLE_SLUG],
  ['group', EXAMPLE_SLUG],
  ['family', EXAMPLE_SLUG],
  ['format', 'json'],
  ['encoding', 'utf-8'],
  ['mode', 'default'],
  ['variant', 'default'],
  ['template', 'default'],
  ['operation', 'create'],
  ['action', 'create'],
  ['method', 'GET'],
  ['status', 'active'],
  ['state', 'active'],
  ['phase', 'active'],
  ['stage', 'active'],
  ['priority', 'normal'],
  ['severity', 'toast'],
  ['level', 'info'],
  ['visibility', 'public'],
  ['scope', 'public'],
  ['privacy', 'public'],
  ['privacyLevel', 'public'],
  ['reactionType', 'like'],
  ['rangeKey', 'last_30_days'],
  ['range', 'last_30_days'],
  ['sortBy', 'createdAt'],
  ['sortOrder', 'desc'],
  ['orderBy', 'createdAt'],
  ['orderDirection', 'desc'],
  ['direction', 'desc'],
  ['filter', EXAMPLE_SLUG],
  ['query', 'fixture'],
  ['q', 'fixture'],
  ['search', 'fixture'],
  ['searchTerm', 'fixture'],
  ['keyword', 'fixture'],
  ['term', 'fixture'],
  ['semanticKind', 'work_experience'],
  ['kind:slug', 'work_experience'],
  ['enabled', 'true'],
  ['disabled', 'false'],
  ['isActive', 'true'],
  ['isPublic', 'true'],
  ['isPublished', 'true'],
  ['isDeleted', 'false'],
  ['isAnonymous', 'false'],
  ['isSystem', 'false'],
  ['isVerified', 'true'],
  ['isFeatured', 'false'],
  ['isPinned', 'false'],
  ['isArchived', 'false'],
  ['isHidden', 'false'],
  ['isLiked', 'false'],
  ['isBookmarked', 'false'],
  ['isReposted', 'false'],
  ['isFollowing', 'false'],
  ['hasMore', 'false'],
  ['hasNextPage', 'false'],
  ['hasVoted', 'false'],
  ['hasCompleted', 'false'],
  ['hasOnboarded', 'true'],
  ['hasCompletedOnboarding', 'true'],
  ['emailNotifications', 'true'],
  ['marketingEmails', 'false'],
  ['weeklyDigest', 'false'],
  ['emailMilestones', 'false'],
  ['emailShareExpiring', 'false'],
  ['resumeExpiryAlerts', 'false'],
  ['allowSearchEngineIndex', 'false'],
  ['showEmail', 'false'],
  ['showPhone', 'false'],
  ['includePhotoInExport', 'true'],
  ['twoFactorRequired', 'false'],
  ['twoFactorEnabled', 'false'],
  ['voted', 'false'],
  ['voteIndex', '0'],
  ['myVoteIndex', '0'],
  ['popularity', '50'],
  ['likes', '10'],
  ['dislikes', '0'],
  ['views', '100'],
  ['shares', '5'],
  ['reposts', '2'],
  ['comments', '3'],
  ['bookmarks', '1'],
  ['followers', '0'],
  ['following', '0'],
  ['connections', '0'],
  ['endorsers', '0'],
  ['endorsements', '0'],
  ['likesCount', '10'],
  ['repostsCount', '2'],
  ['commentsCount', '3'],
  ['bookmarksCount', '1'],
  ['votesCount', '5'],
  ['endorsersCount', '0'],
  ['endorsementsCount', '0'],
  ['readCount', '10'],
  ['shareCount', '5'],
  ['unread', '0'],
  ['unreadCount', '0'],
  ['mentions', '0'],
  ['repliesCount', '0'],
  ['itemsCount', '0'],
  ['totalCount', '0'],
  ['daysAgo', '30'],
  ['minutesAgo', '5'],
  ['durationMs', '1000'],
  ['durationSeconds', '60'],
  ['durationMinutes', '5'],
  ['ttlSeconds', '300'],
  ['ttlMs', '300000'],
  ['retryAfter', '60'],
  ['retryCount', '0'],
  ['attempts', '1'],
  ['attempt', '1'],
  ['maxAttempts', '3'],
  ['progress', '50'],
  ['percent', '50'],
  ['percentage', '50'],
  ['ratio', '0.5'],
  ['multiplier', '1'],
  ['factor', '1'],
  ['confidence', '0.95'],
  ['threshold', '70'],
  ['minLength', '0'],
  ['maxLength', '100'],
  ['minScore', '0'],
  ['maxScore', '100'],
  ['minSalary', '50000'],
  ['maxSalary', '100000'],
  ['minYears', '0'],
  ['maxYears', '20'],
  ['experienceYears', '5'],
  ['yearsOfExperience', '5'],
  ['monthsOfExperience', '60'],
  ['minEnglishLevel', 'B2'],
  ['englishLevel', 'B2'],
  ['proficiency', 'INTERMEDIATE'],
  ['proficiencyLevel', 'INTERMEDIATE'],
  ['cefrLevel', 'B2'],
  ['paymentCurrency', 'BRL'],
  ['currency', 'BRL'],
  ['remotePolicy', 'REMOTE'],
  ['employmentType', 'FULL_TIME'],
  ['contractType', 'FULL_TIME'],
  ['jobType', 'FULL_TIME'],
  ['workSchedule', 'STANDARD'],
  ['applyMode', 'ONE_CLICK'],
  ['defaultExportFormat', 'pdf'],
  ['profileVisibility', 'public'],
  ['digestFrequency', 'DAILY'],
  ['notificationType', 'POST_LIKED'],
  ['eventType', 'JOB_VIEWED'],
  ['error', 'fixture error'],
  ['errorCode', 'FIXTURE_ERROR'],
  ['errorMessage', 'fixture error'],
  ['statusCode', '200'],
  ['httpStatus', '200'],
  ['environment', 'test'],
  ['env', 'test'],
  ['region', 'sa-east-1'],
  ['zone', 'sa-east-1a'],
  ['cluster', 'fixture-cluster'],
  ['service', 'fixture-service'],
  ['component', 'fixture-component'],
  ['module', 'fixture-module'],
  ['skill', EXAMPLE_NAME],
  ['skillName', EXAMPLE_NAME],
  ['skills', EXAMPLE_NAME],
  ['hardSkills', EXAMPLE_NAME],
  ['softSkills', EXAMPLE_NAME],
  ['hashtags', EXAMPLE_TAG],
  ['tags', EXAMPLE_TAG],
  ['keywords', EXAMPLE_TAG],
  ['categories', EXAMPLE_SLUG],
  ['interests', EXAMPLE_SLUG],
  ['industries', EXAMPLE_SLUG],
  ['niches', EXAMPLE_SLUG],
  ['areas', EXAMPLE_SLUG],
  ['companies', EXAMPLE_NAME],
  ['company', EXAMPLE_NAME],
  ['employer', EXAMPLE_NAME],
  ['institution', EXAMPLE_NAME],
  ['organization', EXAMPLE_NAME],
  ['school', EXAMPLE_NAME],
  ['university', EXAMPLE_NAME],
  ['major', EXAMPLE_NAME],
  ['degree', 'Bachelor'],
  ['fieldOfStudy', EXAMPLE_NAME],
  ['program', EXAMPLE_NAME],
  ['certificate', EXAMPLE_NAME],
  ['certification', EXAMPLE_NAME],
  ['issuer', EXAMPLE_NAME],
  ['credentialId', EXAMPLE_SLUG],
  ['credentialUrl', EXAMPLE_URL],
  ['highlight', EXAMPLE_DESCRIPTION],
  ['highlights', EXAMPLE_DESCRIPTION],
  ['responsibility', EXAMPLE_DESCRIPTION],
  ['responsibilities', EXAMPLE_DESCRIPTION],
  ['achievement', EXAMPLE_DESCRIPTION],
  ['achievements', EXAMPLE_DESCRIPTION],
  ['accomplishment', EXAMPLE_DESCRIPTION],
  ['accomplishments', EXAMPLE_DESCRIPTION],
  ['detail', EXAMPLE_DESCRIPTION],
  ['details', EXAMPLE_DESCRIPTION],
  ['notesEn', EXAMPLE_DESCRIPTION],
  ['notesPtBr', `${EXAMPLE_DESCRIPTION} (pt-BR)`],
  ['summaryEn', EXAMPLE_DESCRIPTION],
  ['summaryPtBr', `${EXAMPLE_DESCRIPTION} (pt-BR)`],
  ['contentEn', EXAMPLE_DESCRIPTION],
  ['contentPtBr', `${EXAMPLE_DESCRIPTION} (pt-BR)`],
  ['default', EXAMPLE_SLUG],
  ['fallback', EXAMPLE_SLUG],
  ['initial', EXAMPLE_SLUG],
  ['preset', EXAMPLE_SLUG],
  ['variantId', EXAMPLE_SLUG],
  ['variantTag', EXAMPLE_SLUG],
  ['itemKind', EXAMPLE_SLUG],
  ['kindKey', EXAMPLE_SLUG],
  ['categoryKey', EXAMPLE_SLUG],
  ['groupKey', EXAMPLE_SLUG],
  ['scopeKey', EXAMPLE_SLUG],
  ['typeKey', EXAMPLE_SLUG],
  ['eventName', EXAMPLE_SLUG],
  ['actionName', EXAMPLE_SLUG],
  ['featureName', EXAMPLE_SLUG],
  ['flagName', EXAMPLE_SLUG],
  ['stageName', EXAMPLE_SLUG],
  ['stepName', EXAMPLE_SLUG],
  ['ruleName', EXAMPLE_SLUG],
  ['policyName', EXAMPLE_SLUG],
  ['permissionName', EXAMPLE_SLUG],
  ['roleName', EXAMPLE_SLUG],
  ['groupName', EXAMPLE_SLUG],
  ['departmentName', EXAMPLE_SLUG],
  ['levelName', EXAMPLE_SLUG],
  ['areaName', EXAMPLE_SLUG],
  ['nicheName', EXAMPLE_SLUG],
  ['skillKey', EXAMPLE_SLUG],
  ['languageCode', 'en'],
  ['languageName', 'English'],
  ['localeName', 'English'],
  ['cefr', 'B2'],
]);

// Recursive bounded patterns deliberately written without z.lazy — walking
// them would either descend forever or report each level separately.
// Populated lazily as the backlog reveals them.
const EXEMPT_SCHEMAS: ZodSchema<unknown>[] = [];

function formatOffender(
  route: Route,
  category: 'params' | 'query' | 'body' | 'response',
  path: readonly string[],
  zodType: string,
): string {
  return `${route.method} ${route.path} :: ${category}.${path.join('.')} (${zodType})`;
}

describe('Route examples contract', () => {
  test('every leaf in route.params/query/body/response declares .openapi({ example })', () => {
    const offenders: string[] = [];
    for (const { route } of collected) {
      const categories: Array<{
        key: 'params' | 'query' | 'body' | 'response';
        schema: ZodSchema<unknown> | undefined;
      }> = [
        { key: 'params', schema: route.params },
        { key: 'query', schema: route.query },
        { key: 'body', schema: route.body },
        { key: 'response', schema: route.response },
      ];
      for (const { key, schema } of categories) {
        if (!schema) continue;
        const found = findOffenders(schema, {
          schemaName: `${route.method} ${route.path}`,
          exemptSchemas: EXEMPT_SCHEMAS,
          nameToExample: NAME_TO_EXAMPLE,
        });
        for (const off of found) {
          offenders.push(formatOffender(route, key, off.path, off.zodType));
        }
      }
    }

    if (offenders.length > 0) {
      // Surface the count up front so devs see the backlog magnitude
      // before scrolling through entries.
      console.warn(`route-examples contract: ${offenders.length} offenders`);
    }
    expect(offenders).toEqual([]);
  });
});
