import type { Industry } from '../../interfaces';

export const INDUSTRY_KEYWORDS: Record<Industry, string[]> = {
  software_engineering: [
    'JavaScript',
    'TypeScript',
    'React',
    'Node.js',
    'Python',
    'Java',
    'AWS',
    'Docker',
    'Kubernetes',
    'CI/CD',
    'Git',
    'REST',
    'GraphQL',
    'SQL',
    'NoSQL',
    'Agile',
    'Scrum',
    'microservices',
    'TDD',
    'API',
  ],
  data_science: [
    'Python',
    'R',
    'SQL',
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'Statistics',
    'Data Visualization',
    'Tableau',
    'Power BI',
    'Big Data',
    'Spark',
    'Hadoop',
  ],
  devops: [
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'CI/CD',
    'Linux',
    'Bash',
    'Python',
    'Monitoring',
    'Prometheus',
    'Grafana',
    'Infrastructure',
  ],
  product_management: [
    'Agile',
    'Scrum',
    'Product Strategy',
    'Roadmap',
    'User Research',
    'A/B Testing',
    'Analytics',
    'KPIs',
    'OKRs',
    'Stakeholder Management',
    'Prioritization',
    'User Stories',
    'JIRA',
    'Confluence',
  ],
  design: [
    'Figma',
    'Sketch',
    'Adobe XD',
    'UI/UX',
    'User Research',
    'Wireframing',
    'Prototyping',
    'Design Systems',
    'Responsive Design',
    'Accessibility',
    'Visual Design',
    'Typography',
  ],
  marketing: [
    'SEO',
    'SEM',
    'Content Marketing',
    'Social Media',
    'Analytics',
    'Google Analytics',
    'Email Marketing',
    'CRM',
    'HubSpot',
    'Salesforce',
    'PPC',
    'Brand Strategy',
  ],
  finance: [
    'Financial Analysis',
    'Excel',
    'SQL',
    'Python',
    'Bloomberg',
    'Risk Management',
    'Valuation',
    'Financial Modeling',
    'Accounting',
    'Compliance',
    'Investment',
  ],
  healthcare: [
    'Clinical',
    'Patient Care',
    'HIPAA',
    'EMR',
    'EHR',
    'Healthcare Administration',
    'Medical Terminology',
    'Research',
    'Compliance',
  ],
  education: [
    'Curriculum Development',
    'Teaching',
    'Assessment',
    'Learning Management',
    'EdTech',
    'Student Engagement',
    'Classroom Management',
  ],
  other: [],
};
