import { PersonaConfig } from './persona-config.interface';
import { TechPersona } from './tech-persona.enum';

export const BACKEND_PERSONA: PersonaConfig = {
  id: TechPersona.BACKEND,
  name: 'Backend Developer',
  description: 'APIs, Databases, Microservices, Architecture',
  icon: '⚡',
  primaryColor: '#3B82F6',
  accentColor: '#2563EB',
  gradient: ['#3B82F6', '#8B5CF6'],
  skillCategories: [
    'Programming Languages',
    'Frameworks',
    'Databases',
    'API Design',
    'Microservices',
    'System Design',
    'Performance Optimization',
  ],
  achievementTypes: [
    'system_performance',
    'scalability_achievement',
    'api_usage',
    'open_source_library',
  ],
  prioritySections: ['experiences', 'openSource', 'projects', 'certifications'],
  keywords: [
    'nodejs',
    'python',
    'java',
    'go',
    'rust',
    'c#',
    'spring-boot',
    'django',
    'fastapi',
    'express',
    'nestjs',
    'postgresql',
    'mongodb',
    'redis',
    'rabbitmq',
    'kafka',
    'grpc',
    'microservices',
    'ddd',
  ],
};
