import { TechPersonaEnum } from '@/bounded-contexts/platform/domain/enums';
import { PersonaConfig } from './persona-config.interface';

export const DEVOPS_PERSONA: PersonaConfig = {
  id: TechPersonaEnum.DEVOPS,
  name: 'DevOps Engineer',
  description: 'Infrastructure, Automation, CI/CD',
  icon: '⚙️',
  primaryColor: '#FF6B6B',
  accentColor: '#FFA500',
  gradient: ['#FF6B6B', '#FF8E53'],
  skillCategories: [
    'Infrastructure as Code',
    'CI/CD',
    'Containers & Orchestration',
    'Cloud Platforms',
    'Monitoring & Observability',
    'Configuration Management',
    'Scripting & Automation',
  ],
  achievementTypes: [
    'infrastructure_scale',
    'deployment_frequency',
    'uptime_achievement',
    'cost_optimization',
  ],
  contentPriorities: ['open_source_work', 'credentials', 'thought_leadership', 'career_history'],
  keywords: [
    'kubernetes',
    'docker',
    'terraform',
    'ansible',
    'jenkins',
    'gitlab-ci',
    'aws',
    'azure',
    'gcp',
    'prometheus',
    'grafana',
    'elk',
    'datadog',
    'helm',
    'argocd',
    'istio',
    'vault',
    'consul',
  ],
};
