import { PersonaConfig } from './persona-config.interface';
import { TechPersona } from './tech-persona.enum';

export const FULLSTACK_PERSONA: PersonaConfig = {
  id: TechPersona.FULLSTACK,
  name: 'Full Stack Developer',
  description: 'Frontend, Backend, Databases, APIs',
  icon: '💻',
  primaryColor: '#10B981',
  accentColor: '#059669',
  gradient: ['#10B981', '#3B82F6'],
  skillCategories: [
    'Frontend Frameworks',
    'Backend Technologies',
    'Databases',
    'API Development',
    'DevOps Basics',
    'UI/UX',
    'Testing',
  ],
  achievementTypes: ['github_stars', 'npm_downloads', 'open_source_contribution', 'hackathon_win'],
  prioritySections: ['projects', 'openSource', 'experiences', 'hackathons'],
  keywords: [
    'react',
    'vue',
    'angular',
    'nodejs',
    'express',
    'nestjs',
    'typescript',
    'javascript',
    'mongodb',
    'postgresql',
    'redis',
    'graphql',
    'rest',
    'docker',
    'git',
    'aws',
    'vercel',
    'nextjs',
    'tailwind',
  ],
};
