import { TechPersona } from './tech-persona.enum';
import { PersonaConfig } from './persona-config.interface';

export const SECURITY_PERSONA: PersonaConfig = {
  id: TechPersona.SECURITY,
  name: 'Security Specialist',
  description: 'Cybersecurity, Pentesting, Ethical Hacking',
  icon: '🛡️',
  primaryColor: '#DC2626',
  accentColor: '#B91C1C',
  gradient: ['#DC2626', '#7C2D12'],
  skillCategories: [
    'Penetration Testing',
    'Vulnerability Assessment',
    'Security Tools',
    'Cryptography',
    'Network Security',
    'Application Security',
    'Incident Response',
  ],
  achievementTypes: [
    'cve_discovered',
    'bug_bounty_total',
    'ctf_wins',
    'hall_of_fame',
  ],
  prioritySections: [
    'bugBounties',
    'certifications',
    'publications',
    'achievements',
  ],
  keywords: [
    'oscp',
    'ceh',
    'cissp',
    'burp-suite',
    'metasploit',
    'nmap',
    'wireshark',
    'owasp',
    'xss',
    'sql-injection',
    'csrf',
    'pentesting',
    'red-team',
    'blue-team',
    'soc',
    'siem',
    'ids',
    'ips',
    'forensics',
  ],
};
