/**
 * Application Constants - Re-export for backward compatibility
 *
 * This file has been refactored. All constants are now split into
 * smaller files under ./config/ directory.
 *
 * @see ./config/index.ts for the new structure
 * @deprecated Import directly from './config' instead
 */

import {
  APP_CONFIG,
  RATE_LIMIT_CONFIG,
  FILE_UPLOAD_CONFIG,
  EXPORT_CONFIG,
  CACHE_CONFIG,
  CRYPTO_CONSTANTS,
  API_LIMITS,
  TIME_MS,
  TOKEN_EXPIRY,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
} from './config';

// Re-export everything
export {
  CRYPTO_CONSTANTS,
  API_LIMITS,
  TIME_MS,
  TOKEN_EXPIRY,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
};

// Legacy APP_CONSTANTS for backward compatibility
export const APP_CONSTANTS = {
  JWT_EXPIRATION: APP_CONFIG.JWT_EXPIRATION,
  BCRYPT_ROUNDS: APP_CONFIG.BCRYPT_ROUNDS,
  RATE_LIMIT_TTL: RATE_LIMIT_CONFIG.TTL,
  RATE_LIMIT_MAX_REQUESTS: RATE_LIMIT_CONFIG.MAX_REQUESTS,
  AUTH_RATE_LIMIT_MAX_REQUESTS: RATE_LIMIT_CONFIG.AUTH_MAX_REQUESTS,
  DEFAULT_PAGE_SIZE: APP_CONFIG.DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE: APP_CONFIG.MAX_PAGE_SIZE,
  SEARCH_DEFAULT_LIMIT: APP_CONFIG.SEARCH_DEFAULT_LIMIT,
  SEARCH_AUTOCOMPLETE_LIMIT: APP_CONFIG.SEARCH_AUTOCOMPLETE_LIMIT,
  SEARCH_MAX_RESULTS: APP_CONFIG.SEARCH_MAX_RESULTS,
  MAX_FILE_SIZE: FILE_UPLOAD_CONFIG.MAX_SIZE,
  ALLOWED_IMAGE_TYPES: FILE_UPLOAD_CONFIG.ALLOWED_IMAGE_TYPES,
  PUPPETEER_TIMEOUT: EXPORT_CONFIG.PUPPETEER_TIMEOUT,
  PDF_MAX_PAGES: EXPORT_CONFIG.PDF_MAX_PAGES,
  CACHE_TTL_SHORT: CACHE_CONFIG.TTL_SHORT,
  CACHE_TTL_MEDIUM: CACHE_CONFIG.TTL_MEDIUM,
  CACHE_TTL_LONG: CACHE_CONFIG.TTL_LONG,
  ONBOARDING_MAX_RETRY_ATTEMPTS: APP_CONFIG.ONBOARDING_MAX_RETRY_ATTEMPTS,
} as const;
