export const ERROR_CODES = {
 UNKNOWN: "UNKNOWN",
 INTERNAL_ERROR: "INTERNAL_ERROR",
 BAD_REQUEST: "BAD_REQUEST",
 VALIDATION_ERROR: "VALIDATION_ERROR",
 UNAUTHORIZED: "UNAUTHORIZED",
 FORBIDDEN: "FORBIDDEN",
 NOT_FOUND: "NOT_FOUND",
 CONFLICT: "CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
