services:
  redis:
    extends:
      file: redis.yml
      service: redis
    restart: "no"
    command: redis-server --appendonly no
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
