name: _infrastructure-integration

on:
  workflow_call:

jobs:
  test:
    uses: ./.github/workflows/_infrastructure-test-template.yml
    with:
      test-command: "bun test --config=bunfig.integration.toml"
      test-name: "Integration"
      db-name: "integration_test_db"
      timeout: 15
    secrets: inherit
