name: _static-analysis

on:
  workflow_call:

jobs:
  test:
    uses: octopus-synapse/octopus-workflows/.github/workflows/_static-analysis-template.yml@v1
    with:
      test-command: "bun test --config=config/bunfig.static-analysis.toml"
      test-name: "Static analysis"
      timeout: 10
    secrets: inherit
